/**
 * QVAC SDK Worker Entry (auto-generated layout)
 * Generated by: npx qvac bundle sdk
 * Plugins: 2
 *
 *   - @qvac/sdk/llamacpp-completion/plugin
 *   - @qvac/sdk/llamacpp-embedding/plugin
 *
 * The file is committed so a clean checkout works. Regenerate it whenever
 * `qvac.config.json` changes:  npx qvac bundle sdk
 */

import { initializeWorkerCore, ensureRPCSetup } from '@qvac/sdk/worker-core';
import { registerPlugin } from '@qvac/sdk/plugins';
import { getServerLogger } from '@qvac/sdk/logging';

import { llmPlugin } from '@qvac/sdk/llamacpp-completion/plugin';
import { embeddingsPlugin } from '@qvac/sdk/llamacpp-embedding/plugin';

const { hasRPCConfig } = initializeWorkerCore();

const logger = getServerLogger();
logger.info('Resonance QVAC Worker');
logger.info('Plugins: 2');

registerPlugin(llmPlugin);
registerPlugin(embeddingsPlugin);

if (hasRPCConfig) {
  ensureRPCSetup();
}
